# frozen_string_literal: true

module ::LinkSafety
  class Extractor
    Extraction = Data.define(:urls, :error_code) do
      def success? = error_code.blank?
    end

    def self.post_raw_result(raw, topic_id, user: nil)
      return Extraction.new(urls: [], error_code: nil) if raw.blank?

      # Use the same Discourse cooking/onebox pipeline that posts use, then
      # extract navigation targets from the cooked result. PostAnalyzer#raw_links
      # deliberately omits some onebox sources, while cooked extraction sees
      # both ordinary links and full/inline onebox source URLs. Internal links
      # generated by mentions, hashtags and quotes are removed by the central
      # candidate classifier rather than by hardcoded Discourse route checks.
      analyzer = ::PostAnalyzer.new(raw, topic_id)
      cooked = analyzer.cook(raw, topic_id: topic_id, user_id: user&.id)
      post_cooked_result(cooked)
    rescue => e
      Rails.logger.warn("[LinkSafety] post link extraction failed class=#{e.class.name}")
      ::LinkSafety::HealthRegistry.control_failure!(component: :extractor, code: e.class.name)
      Extraction.new(urls: [], error_code: "extractor_failure")
    end

    ONEBOX_MARKER_ATTRIBUTE = "data-link-safety-onebox-source".freeze

    def self.post_cooked_result(cooked)
      return Extraction.new(urls: [], error_code: nil) if cooked.blank?

      doc = Nokogiri::HTML5.fragment(cooked)

      # PostStripper intentionally removes onebox elements before ordinary link
      # analysis. Preserve only each onebox's navigation source in a temporary
      # marker placed beside the onebox. Because the marker lives inside the
      # same parent, core/plugin strippers that remove an elided/custom parent
      # also remove the marker; this keeps PostStripper semantics intact without
      # losing legitimate onebox coverage.
      mark_onebox_sources!(doc)
      ::PostStripper.strip(doc)
      onebox_urls = take_marked_onebox_sources!(doc)

      urls = ::PrettyText.extract_links(doc.to_html).map(&:url).compact
      urls.concat(quote_anchor_urls(doc))
      urls.concat(onebox_urls)
      urls = ::LinkSafety::UrlCandidateClassifier.filter(urls)
      Extraction.new(urls: urls, error_code: nil)
    rescue => e
      Rails.logger.warn("[LinkSafety] post cooked link extraction failed class=#{e.class.name}")
      ::LinkSafety::HealthRegistry.control_failure!(component: :extractor, code: e.class.name)
      Extraction.new(urls: [], error_code: "extractor_failure")
    end

    def self.mark_onebox_sources!(doc)
      doc.css("aside.onebox[data-onebox-src], a.onebox[href]").each do |node|
        source = node["data-onebox-src"].presence || node["href"].presence
        next if source.blank?

        marker = Nokogiri::XML::Node.new("span", doc.document)
        marker[ONEBOX_MARKER_ATTRIBUTE] = source
        node.add_previous_sibling(marker)
      end
    end
    private_class_method :mark_onebox_sources!

    def self.take_marked_onebox_sources!(doc)
      markers = doc.css("[#{ONEBOX_MARKER_ATTRIBUTE}]")
      urls = markers.filter_map { |marker| marker[ONEBOX_MARKER_ATTRIBUTE].presence }
      markers.remove
      urls
    end
    private_class_method :take_marked_onebox_sources!

    def self.quote_anchor_urls(doc)
      doc.css("aside.quote a[href]").filter_map do |anchor|
        next if anchor.ancestors.any? do |ancestor|
          classes = ancestor["class"].to_s.split
          classes.include?("onebox") || classes.include?("elided")
        end

        anchor["href"].presence
      end
    end
    private_class_method :quote_anchor_urls

    def self.chat_message_result(message, user: nil, author_username: nil)
      return Extraction.new(urls: [], error_code: nil) if message.blank? || !defined?(::Chat::Message)
      cooked = ::Chat::Message.cook(
        message,
        user_id: user&.id,
        author_username: author_username || user&.username,
      )
      cooked_result(cooked)
    rescue => e
      Rails.logger.warn("[LinkSafety] chat link extraction failed class=#{e.class.name}")
      ::LinkSafety::HealthRegistry.control_failure!(component: :extractor, code: e.class.name)
      Extraction.new(urls: [], error_code: "extractor_failure")
    end

    def self.markdown_result(raw)
      return Extraction.new(urls: [], error_code: nil) if raw.blank?
      cooked_result(::PrettyText.cook(raw))
    rescue => e
      Rails.logger.warn("[LinkSafety] markdown link extraction failed class=#{e.class.name}")
      ::LinkSafety::HealthRegistry.control_failure!(component: :extractor, code: e.class.name)
      Extraction.new(urls: [], error_code: "extractor_failure")
    end

    def self.cooked_result(cooked)
      return Extraction.new(urls: [], error_code: nil) if cooked.blank?

      doc = Nokogiri::HTML5.fragment(cooked)
      urls = ::PrettyText.extract_links(doc.to_html).map(&:url).compact
      urls.concat(quote_anchor_urls(doc))
      urls = ::LinkSafety::UrlCandidateClassifier.filter(urls)
      Extraction.new(urls: urls, error_code: nil)
    rescue => e
      Rails.logger.warn("[LinkSafety] cooked link extraction failed class=#{e.class.name}")
      ::LinkSafety::HealthRegistry.control_failure!(component: :extractor, code: e.class.name)
      Extraction.new(urls: [], error_code: "extractor_failure")
    end

    # Backwards-compatible array helpers for non-validation callers such as
    # pending scheduling. Security-sensitive validation uses the result methods
    # above so extraction failures cannot silently become an empty URL list.
    def self.from_post_raw(raw, topic_id, user: nil)
      post_raw_result(raw, topic_id, user: user).urls
    end

    def self.from_chat_message(message, user: nil, author_username: nil)
      chat_message_result(message, user: user, author_username: author_username).urls
    end

    def self.from_cooked(cooked)
      cooked_result(cooked).urls
    end
  end
end
